---
- hosts: all
  become: true
  tasks:

  

          - name: install apache2
            apt:
                    name: apache2
          - name: install php
            apt:
                    name: libapache2-mod-php

